name: Cypress end-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.7
        env:
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000
